### ISSUE TITLE
KALLITHEA_LOCALE should be en_US.UTF-8

### ISSUE THREAD

**Issue by windymindy** [n-at/docker-kallithea#5]
Add beaker.session.cookie_expires = 2592000 to make session cookie persist after closing browser.
`sudo sed -ri 's/^(beaker.session.timeout = 2592000)$/\1\n## default cookie expiration time in seconds, set to `true` to set expire\n## at browser close\nbeaker.session.cookie_expires = 2592000/' /data/srv/docker/kallithea/config/kallithea.ini`

You will see in chrome dev tools, that kallithea sends cookie with 'expires' filed in wrong date time format. It will be 
`set-cookie: kallithea=bfc24b5de2a67f2bd21260c0a76586fa6309ef50ef29b8aa862c49b08d6053c8d4d59928; expires=Tue, 10-Июл-2018 19:22:07 GMT; httponly; Path=/; secure`
while it should be 10-Jul-2018. This is a bug somewhere in beaker or php. It should use DateTime::COOKIE format instead of LC_TIME="ru_RU.UTF-8".
But if you set locale to en_US.UTF-8, commit messages are shown just fine and russian full-text search also works well.

P.S. how do you deal with russian filenames?

**Comment by n-at** [comment]
Fixed.

> P.S. how do you deal with russian filenames?

We just don't use russian filenames at all.
